### ISSUE TITLE
Alternative generation rule for GENERATED_BY

### ISSUE THREAD

**Issue by nigel-parker** [nigel-parker/gedinline#1]
From @coret:

About 50 GEDCOM's show a "Submitted by                   Unknown"
And associated warning "*** Line 2:       Invalid content for SOUR tag: '' missing value for <APPROVED_SYSTEM_ID>"

I checked some files and saw the following (invalid GEDCOM):
0 HEAD
1 SOUR
2 NAME MacFamilyTree

I don't know if it's possible, but in case 0 HEAD 1 SOUR has no value, the 0 HEAD 1 SOUR 2 NAME could be used for GENERATED_BY.

**Comment by nigel-parker** [comment]
@coret: Is there a confusion here?

HEAD.SOUR maps to GENERATED_BY, whereas
SUBM.NAME maps to SUBMITTED_BY.

Was your intention to change the logic of GENERATED_BY?

**Comment by coret** [comment]
Yes, my intention is to change the logic of **GENERATED_BY**.

In the examples mentioned I see:
> Generated by                   
> Submitted by                   Unknown

The "Submitted by" can't be fixed, but the empty "Generated by" can be.
