### ISSUE TITLE
5.5.1 validation incorrectly reports empty ADDR line value as error.

### ISSUE THREAD

**Issue by changeling** [nigel-parker/gedinline#10]
Given files formatted under the revised 5.5.1 specification, 5.5.1 validation reports empty ADDR line value as error, though the revised 5.5.1 explicitly calls for that. This is a point of confusion for some, as the original 1999 5.5.1 Draft calls for ADDR with value, while the 2019 Revision 2 presented as canon on the gedcom.org site disallows ADDR with value.

From the GEDCOM 5.5.5 Specification at https://www.gedcom.org/gedcom.html:

```
ADDRESS_STRUCTURE:=
n ADDR
+1 ADR1 <ADDRESS_LINE1>
+1 ADR2 <ADDRESS_LINE2>
+1 ADR3 <ADDRESS_LINE3>
+1 CITY <ADDRESS_CITY>
+1 STAE <ADDRESS_STATE>
+1 POST <ADDRESS_POSTAL_CODE> +1 CTRY <ADDRESS_COUNTRY>
```

"The GEDCOM 5.5.1 Annotated Edition (2018) explicitly deprecated the old style, unstructured addresses. GEDCOM 5.5.5 supports structured addresses exclusively. The ADDR line must not have a line value."

From the Annotated 5.5.1 Revision 2 at https://www.gedcom.org/gedcom.html:

"__Old Style versus New Style addresses__
GEDCOM 5.5.1 supports two address styles; old style and new style. The old style address is the ADDR line value (and its subordinate CONT line values): a single value split over several lines. The new style address, introduced in GEDCOM 5.4, is a structured format that uses the ADDR subrecords. A single address can be specified both ways at once.
The FamilySearch GEDCOM 5.5.1 specification demands the use of old-style addresses, by stating that, for
backward compatibility, the new style should not be used in lieu of the required ADDR and CONT line
structure. That requirement made sense back in 1999, when GEDCOM 5.5 was only four years old yet, but
makes no sense anymore. Today (2018 CE), GEDCOM writers should be using the new style address
exclusively. The ADDR line value should not be used, but considered deprecated."

From the 1999 5.5.1 Draft Specification:

"The address structure should be formed as it would appear on a mailing label using the ADDR and the CONT lines to form the address structure. The ADDR and CONT lines are required for any address. The additional subordinate address tags such as STAE and CTRY are provided to be used by systems that have structured their addresses for indexing and sorting. For backward compatibility these lines are not to be used in lieu of the required ADDR.and CONT line structure."

An argument can be, I think, made and well-sustained that the ADDR line _may_ be empty, with a CONT carrying the initial line value. I don't see any clear prohibition of an empty ADDR, only a requirement that it exist. By my reading (and I'm happy to be corrected) a structure such as:

```
1 ADDR 
2 CONT 123 Any Street
2 CONT Anywhere, Anytown ACountry
...
```
would be legal under even the draft specification.

```
...
GEDCOM version in file         5.5.1
GEDCOM version assumed         5.5.1

...
*** Line 11:      Invalid content for ADDR tag: '' missing value for <ADDRESS_LINE>
*** Line 21:      Invalid content for ADDR tag: '' missing value for <ADDRESS_LINE>
*** Line 91:      Invalid content for ADDR tag: '' missing value for <ADDRESS_LINE>
...
```

```
...
1 SOUR GS
2 NAME GEDCOM Specification
2 VERS 5.5.1
2 CORP gedcom.org
3 ADDR
4 CITY LEIDEN
3 WWW www.gedcom.org
...

...
1 ADDR 
2 ADR1 1900 43rd Street West
2 CITY Billings
2 STAE Montana
2 POST 68051
2 CTRY United States of America
...

...
1 ADDR
2 ADR1 35 N West Temple Street
2 CITY Salt Lake City
2 STAE Utah
2 POST 84150
2 CTRY United States of America
...
```

Using the attached files (`.TXT` because github won't accept `.GED` for attachments):

[551SAMPLE.TXT](https://github.com/nigel-parker/gedinline/files/5361608/551SAMPLE.TXT)
[555SAMPLE.TXT](https://github.com/nigel-parker/gedinline/files/5361609/555SAMPLE.TXT)

**Comment by nigel-parker** [comment]
Thanks for for your clear and well documented suggestion. And again, apologies for the time it has taken to get reply out. 

This question comes down to which version of the spec is used. GED-inline is based on:

- the orginal 1999 spec for 5.5.1
- Tamura Jones' 2019 spec for 5.5.5

I don't see much sign of Tamura's revised/annotated versions of 5.5.1 being widely accepted so far.

I think it is clear that the 1999 spec says an ADDR tag must have an <ADDRESS_LINE> which has a length restriction to {Size=1:60}.
