### ISSUE TITLE
Invalid phonetisation method

### ISSUE THREAD

**Issue by jl5000** [nigel-parker/gedinline#13]
I'm using a GEDCOM 5.5.5 file and the online validator is saying the phonetisation method is invalid: "Invalid content for TYPE tag". However the specification says a user-defined value can be used.

**Comment by nigel-parker** [comment]
Thanks for pointing this out!

**Comment by jl5000** [comment]
What was the reason for reducing the minimum size to 4? Also, I think this issue may also apply to the Romanisation method as well.

I'm not sure why the specification only allows such a short string for these values.

**Comment by nigel-parker** [comment]
I reduced the size to 4 because otherwise 'kana' would have been rejected because of its length. I assume that 5 was just an oversight.

And I think you are right about romanisation_method, and possibly other values.

**Comment by jl5000** [comment]
Ah, good point. Thanks.
