### ISSUE TITLE
Checks for missing family links

### ISSUE THREAD

**Issue by jl5000** [nigel-parker/gedinline#14]
I've noticed that the validator doesn't seem to check for missing family links. For example, a family may reference an individual record as a spouse, but the individual records may be missing a corresponding FAMS subrecord. The validator doesn't pick this up.

**Comment by nigel-parker** [comment]
Thank you for your feedback. The earlier version of the relevant specifications weren't crystal clear on this point. But I see that 7.0 contains an unambiguous demand that they should be there. It should be OK in the latest version.
