### ISSUE TITLE
Obsolete "(excluding upload time)"

### ISSUE THREAD

**Issue by coret** [nigel-parker/gedinline#2]
In the report the "Analysis time" value has a remark "(excluding upload time)". This is a leftover from usage on ged-inline.elasticbeanstalk.com and can be removed from https://github.com/nigel-parker/gedinline/blob/176fceb862abf177dbe349a4a5265f8e3d899c15/src/main/java/gedinline/main/StructureListener.java

**Comment by nigel-parker** [comment]
Well not really... because the library is also used by the GED-inline service. But I could perhaps change the text to be 'excluding any upload time'?

**Comment by coret** [comment]
When you look at the library, there is no upload. The alternative "excluding any upload time" might suggest otherwise. 

The environment where the library is used might have to do with upload, that is where the remark about upload time should be made.
