### ISSUE TITLE
PAGE/QUAY allowed under SOUR (GEDCOM 5.5)

### ISSUE THREAD

**Issue by coret** [nigel-parker/gedinline#5]
Below is a minimal sample of a GEDCOM which produce the following warnings.

*** Line 19:      Tag PAGE is not allowed under SOUR
*** Line 20:      Tag QUAY is not allowed under SOUR

> 0 HEAD
> 1 SOUR FAMILY_HISTORIAN
> 2 VERS 6.2.7
> 2 NAME Family Historian
> 2 CORP Calico Pie Limited
> 1 FILE test_sour_page_quay.ged
> 1 GEDC
> 2 VERS 5.5
> 2 FORM LINEAGE-LINKED
> 1 CHAR ASCII
> 1 SUBM @U1@
> 0 @U1@ SUBM
> 1 NAME XXX
> 0 @I1@ INDI
> 1 NAME XXX /XXX/
> 1 SEX M
> 1 NOTE 
> 2 SOUR @S1@
> 3 PAGE XXX
> 3 QUAY 3
> 0 @S1@ SOUR
> 1 AUTH XXX
> 1 TITL XXX
> 1 PUBL XXX
> 0 TRLR

Based on the [GEDCOM 5.5 specification](http://www.fhug.org.uk/pushfile.php?filename=gedcom55.pdf&name=GEDCOM+Release+5.5+PDF&ns=/fhugdownloads/contents/), I think these warnings are not correct

> NOTE_STRUCTURE:=
> [
> n NOTE @<XREF:NOTE>@ {1:1}
> +1 <<SOURCE_CITATION>> {0:M}
> |
> n NOTE [SUBMITTER_TEXT> | <NULL>] {1:1}
> +1 [ CONC | CONT ] <SUBMITTER_TEXT> {0:M}
> +1 <<SOURCE_CITATION>> {0:M}
> ]
> 
> SOURCE_CITATION:=
> [
> n SOUR @<XREF:SOUR>@ /* pointer to source record */ {1:1}
> +1 PAGE <WHERE_WITHIN_SOURCE> {0:1}
> +1 EVEN <EVENT_TYPE_CITED_FROM> {0:1}
> +2 ROLE <ROLE_IN_EVENT> {0:1}
> +1 DATA {0:1}
> +2 DATE <ENTRY_RECORDING_DATE> {0:1}
> +2 TEXT <TEXT_FROM_SOURCE> {0:M}
> +3 [ CONC | CONT ] <TEXT_FROM_SOURCE> {0:M}
> +1 QUAY <CERTAINTY_ASSESSMENT> {0:1}
> +1 <<MULTIMEDIA_LINK>> {0:M}
> +1 <<NOTE_STRUCTURE>> {0:M}
> | /* Systems not using source records */
> n SOUR <SOURCE_DESCRIPTION> {1:1}
> +1 [ CONC | CONT ] <SOURCE_DESCRIPTION> {0:M}
> +1 TEXT <TEXT_FROM_SOURCE> {0:M}
> +2 [CONC | CONT ] <TEXT_FROM_SOURCE> {0:M}
> +1 <<NOTE_STRUCTURE>> {0:M}
> ]

**Comment by nigel-parker** [comment]
@coret: Are there differing versions of the 5.5 spec? The one I have based GED-inline on is at http://homepages.rootsweb.com/~pmcbride/gedcom/55gctoc.htm and there the NOTE_STRUCTURE looks like
```
NOTE_STRUCTURE: =
  [
  n  NOTE @<XREF:NOTE>@  {1:1}
    +1 SOUR @<XREF:SOUR>@  {0:M}
  |
  n  NOTE [<SUBMITTER_TEXT> | <NULL>]  {1:1}
    +1 [ CONC | CONT ] <SUBMITTER_TEXT>  {0:M}
    +1 SOUR @<XREF:SOUR>@  {0:M}
  ]

SOURce tags subordinate to the note structure can only contain a pointer to an associated source record. Any non-structured reference to a source from a note structure can be included as part of the note text itself.
```
which looks different to the one you quote?

**Comment by coret** [comment]
Ah, seems I came to the same conclusion a while ago, see [Which GEDCOM 5.5 grammar is correct?](https://blog-en.coret.org/2014/12/which-gedcom-55-grammar-is-correct.html) Unfortunatly, On https://www.gedcom.org/versions.html there are 3 versions 5.5 listed. Take a pick :-(

**Comment by nigel-parker** [comment]
Incredible! I had no idea there were several versions.

I will leave the validator as it is now but Ithink I should update the GED-inline server to say which standard it follows.
