### ISSUE TITLE
Build failure in Java 11

### ISSUE THREAD

**Issue by nigel-parker** [nigel-parker/gedinline#7]
From @coret

java --version
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Debian-1deb10u1, mixed mode, sharing)

Results:

Starting a Gradle Daemon (subsequent builds will be faster)
> Task :compileTestGroovy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileTestGroovy'.
> BUG! exception in phase 'class generation' in source unit '/home/http/www.genealogieonline.nl/gedinline2/gedinline-master/src/test/groovy/gedinline/lexical/InputLineSpec.groovy' unsupported Target MODULE

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s

**Comment by changeling** [comment]
Tried with latest commits. Build failing under Java 11.

Ubuntu 18.04

```
$ javac -version
javac 11.0.6

$ java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)
```

Groovy Build Scan:
https://scans.gradle.com/s/7rg2mw5nzp6jk

```
$ ./gradlew --scan gedinline
> Task :compileTestGroovy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileTestGroovy'.
> BUG! exception in phase 'class generation' in source unit '/home/clarson/Desktop/GEDCOM-work/gedinline-test/src/test/groovy/gedinline/lexical/InputLineSpec.groovy' unsupported Target MODULE

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 25s
4 actionable tasks: 4 executed
```

**Comment by nigel-parker** [comment]
Hi

This should now work with the latest commit. Please let me know if you
still experience problems.

mvh
Nigel


man. 9. mar. 2020 kl. 22:18 skrev changeling <notifications@github.com>:

**Comment by changeling** [comment]
MacOS X 10.15.1 

```
$ javac -version
javac 11.0.6
$ java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)
```

```
$ ./gradlew gedinline

> Task :test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/Users/clarson/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy-all/2.4.19/ee2bfd0b63b67e0ebf5a5016daea81479600981e/groovy-all-2.4.19.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

> Task :groovydoc
Trying to override old definition of task fileScanner

BUILD SUCCESSFUL in 17s
8 actionable tasks: 7 executed, 1 up-to-date
```

**Comment by nigel-parker** [comment]
Then everything is working as it should. See this link for a discussion of
the warning messages:

https://issues.apache.org/jira/browse/GROOVY-8339

mvh
Nigel


fre. 27. mar. 2020 kl. 03:07 skrev changeling <notifications@github.com>:

**Comment by changeling** [comment]
I should have clarified my intent. I meant to highlight the 'BUILD SUCCESSFUL in 17s' bit!

Cheers
Chris

**Comment by nigel-parker** [comment]
OK, thanks! :--)

mvh
Nigel


fre. 27. mar. 2020 kl. 15:38 skrev changeling <notifications@github.com>:
