### ISSUE TITLE
DATE_VALUE tests in 5.5.1 are passing full month names as valid, but 5.5.5 is correctly reporting them as invalid.

### ISSUE THREAD

**Issue by changeling** [nigel-parker/gedinline#9]
<DATE_VALUE> tests in 5.5.1 are passing full month names as valid, but 5.5.5 is correctly reporting them as invalid.

Also note that 5.5.1 validation reports excessive length, but not invalid <date_VALUE, while 5.5.5 reports invalid <DATE_VALUE>, but not excessive length.

```
Encoding                       UNICODE
GEDCOM version in file         5.5.1
GEDCOM version assumed         5.5.1

...
Lines                      36  Number of lines in the GEDCOM file
Records                     4  Number of records
Warnings                    2  Total number of warning messages
...

*** Line 25:      Invalid content for DATE tag: 'from 20 November 1345 to 24 February 1367' is more than 40 characters, the maximum length for <DATE_VALUE>
*** Line 28:      Invalid content for DATE tag: 'FROM 20 November 1345 TO 24 February 1367' is more than 40 characters, the maximum length for <DATE_VALUE>
```

```
...
Encoding                       UNICODE
GEDCOM version in file         5.5.5
GEDCOM version assumed         5.5.5

...
Lines                      42  Number of lines in the GEDCOM file
Records                     4  Number of records
Warnings                    3  Total number of warning messages
...

*** Line 25:      Invalid content for DATE tag: 'from 20 November 1345 to 24 February 1367' is not a valid <DATE_VALUE>
*** Line 28:      Invalid content for DATE tag: 'FROM 20 November 1345 TO 24 February 1367' is not a valid <DATE_VALUE>
*** Line 34:      Invalid content for DATE tag: '20 November 1345' is not a valid <DATE_VALUE>
```

Lines in question:
```
1 BIRT 
2 DATE from 20 November 1345 to 24 February 1367
2 PLAC Earth
1 BIRT 
2 DATE FROM 20 November 1345 TO 24 February 1367
2 PLAC Earth
1 BIRT 
2 DATE FROM 20 Nov 1345 TO 24 Feb 1367
2 PLAC Earth
1 BIRT 
2 DATE 20 November 1345
2 PLAC Earth
1 BIRT 
2 DATE 20 Nov 1345
2 PLAC Earth
1 BIRT 
2 DATE 20 NOV 1345
2 PLAC Earth
```

Attached files with `.txt` extension, as github doesn't accept `.ged` for attachment.

[simple-date-test-551.txt](https://github.com/nigel-parker/gedinline/files/5361544/simple-date-test-551.txt)
[simple-date-test-555.txt](https://github.com/nigel-parker/gedinline/files/5361545/simple-date-test-555.txt)

**Comment by nigel-parker** [comment]
Thank you for reporting this. Apologies for the long response time. And how incredible that such an obvious bug has been undiscovered for almost 10 years!

5.5.1: Agreed, GED-inline wrongly accepts long values for Gregorian months.

5.5.5: Actually I don't think there is a bug here. GED-inline normally only reports one warning per line, and whether that turns out to be a length error or a syntax error is not guaranteed. And it does indeed report length warnings for dates. Here is an example: 

        (from 20 November 1345 to 24 February 1367)

**Comment by changeling** [comment]
I'm going to retract this. Something strange (very likely on my end) is happening, but upon downloading a fresh copy and building it, the issue goes away. I suspect you're absolutely correct that something build-related happened, or I somehow misnamed or mismatched a directory. Apologies for not digging in _before_ posting this.
